#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pre_commit
Version  : 2.13.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/4d/ca/1a1d2049851bd45e89916e03a3faaf32743cbf0cb7e4587d89f66915988e/pre_commit-2.13.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/4d/ca/1a1d2049851bd45e89916e03a3faaf32743cbf0cb7e4587d89f66915988e/pre_commit-2.13.0.tar.gz
Summary  : A framework for managing and maintaining multi-language pre-commit hooks.
Group    : Development/Tools
License  : MIT
Requires: pre_commit-bin = %{version}-%{release}
Requires: pre_commit-python = %{version}-%{release}
Requires: pre_commit-python3 = %{version}-%{release}
Requires: PyYAML
Requires: toml
Requires: virtualenv
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : toml
BuildRequires : virtualenv

%description
[![Build Status](https://dev.azure.com/asottile/asottile/_apis/build/status/pre-commit.pre-commit?branchName=master)](https://dev.azure.com/asottile/asottile/_build/latest?definitionId=21&branchName=master)
[![Azure DevOps coverage](https://img.shields.io/azure-devops/coverage/asottile/asottile/21/master.svg)](https://dev.azure.com/asottile/asottile/_build/latest?definitionId=21&branchName=master)
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/pre-commit/pre-commit/master.svg)](https://results.pre-commit.ci/latest/github/pre-commit/pre-commit/master)

%package bin
Summary: bin components for the pre_commit package.
Group: Binaries

%description bin
bin components for the pre_commit package.


%package python
Summary: python components for the pre_commit package.
Group: Default
Requires: pre_commit-python3 = %{version}-%{release}

%description python
python components for the pre_commit package.


%package python3
Summary: python3 components for the pre_commit package.
Group: Default
Requires: python3-core
Provides: pypi(pre_commit)
Requires: pypi(cfgv)
Requires: pypi(identify)
Requires: pypi(nodeenv)
Requires: pypi(pyyaml)
Requires: pypi(toml)
Requires: pypi(virtualenv)

%description python3
python3 components for the pre_commit package.


%prep
%setup -q -n pre_commit-2.13.0
cd %{_builddir}/pre_commit-2.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1623346928
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pre-commit
/usr/bin/pre-commit-validate-config
/usr/bin/pre-commit-validate-manifest

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
